services:

############## BOOT NODES ##############

  fullnode-bcb-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-bcb-1:.
    environment:
      P2P_PORT: 30303
      BESU_IDENTITY: "fullnode-bcb-1"
    entrypoint: ["./entrypoint_bootnode.sh"]

  fullnode-bcb-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-bcb-2:.
    environment:
      P2P_PORT: 30304
      BESU_IDENTITY: "fullnode-bcb-2"
    entrypoint: ["./entrypoint_bootnode.sh"]

  fullnode-selic-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-selic-1:.
    environment:
      P2P_PORT: 30305
      BESU_IDENTITY: "fullnode-selic-1"
    entrypoint: ["./entrypoint_bootnode.sh"]

  fullnode-selic-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-selic-2:.
    environment:
      P2P_PORT: 30306
      BESU_IDENTITY: "fullnode-selic-2"
    entrypoint: ["./entrypoint_bootnode.sh"]
  
############## FULL NODES ##############

  fullnode-parta-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-parta-1:.
    environment:
      P2P_PORT: 30307
      BESU_IDENTITY: "fullnode-parta-1"
      RPC_HTTP_PORT: 8546
    entrypoint: ["./entrypoint_fullnode.sh"]

  fullnode-partb-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-partb-1:.
    environment:
      P2P_PORT: 30308
      BESU_IDENTITY: "fullnode-partb-1"
      RPC_HTTP_PORT: 8547
    entrypoint: ["./entrypoint_fullnode.sh"]

  fullnode-partc-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-partc-1:.
    environment:
      P2P_PORT: 30309
      BESU_IDENTITY: "fullnode-partc-1"
      RPC_HTTP_PORT: 8548
    entrypoint: ["./entrypoint_fullnode.sh"]

  fullnode-partd-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-partd-1:.
    environment:
      P2P_PORT: 30310
      BESU_IDENTITY: "fullnode-partd-1"
      RPC_HTTP_PORT: 8549
    entrypoint: ["./entrypoint_fullnode.sh"]


########### VALIDATOR NODES ############

  validator-bcb-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-bcb-1:.
    environment:
      P2P_PORT: 30311
      BESU_IDENTITY: "validator-bcb-1"
      RPC_HTTP_PORT: 8550
    entrypoint: ["./entrypoint_fullnode.sh"]

  validator-bcb-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-bcb-2:.
    environment:
      P2P_PORT: 30312
      BESU_IDENTITY: "validator-bcb-2"
      RPC_HTTP_PORT: 8551
    entrypoint: ["./entrypoint_fullnode.sh"]

  validator-bcb-3:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-bcb-3:.
    environment:
      P2P_PORT: 30313
      BESU_IDENTITY: "validator-bcb-3"
      RPC_HTTP_PORT: 8552
    entrypoint: ["./entrypoint_fullnode.sh"]

  validator-bcb-4:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-bcb-4:.
    environment:
      P2P_PORT: 30314
      BESU_IDENTITY: "validator-bcb-4"
      RPC_HTTP_PORT: 8553
    entrypoint: ["./entrypoint_fullnode.sh"]

  validator-selic-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-selic-1:.
    environment:
      P2P_PORT: 30315
      BESU_IDENTITY: "validator-selic-1"
      RPC_HTTP_PORT: 8554
    entrypoint: ["./entrypoint_fullnode.sh"]

  validator-selic-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./validator-selic-2:.
    environment:
      P2P_PORT: 30316
      BESU_IDENTITY: "validator-selic-2"
      RPC_HTTP_PORT: 8555
    entrypoint: ["./entrypoint_fullnode.sh"]

############### JD NODES ###############

  fullnode-jd-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-jd-1:.
    environment:
      P2P_PORT: 30317
      BESU_IDENTITY: "fullnode-jd-1"
      RPC_HTTP_PORT: 8556
    entrypoint: ["./entrypoint_fullnode.sh"]

  fullnode-jd-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./fullnode-jd-2:.
    environment:
      P2P_PORT: 30318
      BESU_IDENTITY: "fullnode-jd-2"
      RPC_HTTP_PORT: 8557
    entrypoint: ["./entrypoint_fullnode.sh"]

########################################