services:
########### VALIDATOR NODES ############

  validator-bcb-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/validator-bcb-1:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 1
      BESU_IDENTITY: "validator-bcb-1"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.2

  validator-bcb-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/validator-bcb-2:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 1
      BESU_IDENTITY: "validator-bcb-2"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.3
    depends_on:
      - validator-bcb-1

  validator-selic-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/validator-selic-1:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 1
      BESU_IDENTITY: "validator-selic-1"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.4
    depends_on:
      - validator-bcb-1

  validator-selic-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/validator-selic-2:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 1
      BESU_IDENTITY: "validator-selic-2"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.5
    depends_on:
      - validator-bcb-1

############### JD NODES ###############

  fullnode-jd-1:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/fullnode-jd-1:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 0
      BESU_IDENTITY: "fullnode-jd-1"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.6
    depends_on:
      - validator-bcb-1

  fullnode-jd-2:
    image: "hyperledger/besu:23.7.2"
    volumes:
      - ./nodes/fullnode-jd-2:/node
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VALIDATOR: 0
      BESU_IDENTITY: "fullnode-jd-2"
    entrypoint: ["/entrypoint.sh"]
    networks:
      bacen:
        ipv4_address: 172.21.0.7
    depends_on:
      - validator-bcb-1

########################################

networks:
  bacen:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16