version: '3.6'

x-validator:
  &validator
  restart: "on-failure"
  image: hyperledger/besu:23.7.2
  entrypoint:
    - /bin/bash
    - -c
    - |
      /opt/besu/bin/besu --config-file=/node/config.toml --genesis-file=/node/genesis.json --Xdns-enabled=true --p2p-host=$$(hostname -i) --rpc-http-api=ETH,WEB3,NET,QBFT,ADMIN --rpc-http-host=$$(hostname -i);


x-archivenode:
  &archivenode
  restart: "on-failure"
  image: hyperledger/besu:23.7.2
  entrypoint:
    - /bin/bash
    - -c
    - |
      /opt/besu/bin/besu --config-file=/node/config.toml --genesis-file=/node/genesis.json --Xdns-enabled=true --graphql-http-host=$$(hostname -i) --rpc-ws-host=$$(hostname --i) --p2p-host=$$(hostname -i) --rpc-http-api=ETH,WEB3,NET,QBFT,ADMIN --rpc-http-host=$$(hostname -i);

services:
  validator-bcb-1:
    << : *validator
    volumes:
      - ./nodes/validator-bcb-1:/node
    environment:
      BESU_IDENTITY: "validator-bcb-1"

  validator-bcb-2:
    << : *validator
    volumes:
      - ./nodes/validator-bcb-2:/node
    environment:
      BESU_IDENTITY: "validator-bcb-2"
    depends_on:
      - validator-bcb-1

  validator-selic-1:
    << : *validator
    volumes:
      - ./nodes/validator-selic-1:/node
    environment:
      BESU_IDENTITY: "validator-selic-1"
    depends_on:
      - validator-bcb-1

  validator-selic-2:
    << : *validator
    volumes:
      - ./nodes/validator-selic-2:/node
    environment:
      BESU_IDENTITY: "validator-selic-2"
    depends_on:
      - validator-bcb-1

  archivenode-jd-1:
    << : *archivenode
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    volumes:
      - ./nodes/archivenode-jd-1:/node
    environment:
      BESU_IDENTITY: "archivenode-jd-1"
    depends_on:
      - validator-bcb-1

  archivenode-jd-2:
    << : *archivenode
    # ports:
    #   - "8545:8545"
    #   - "8546:8546"
    volumes:
      - ./nodes/archivenode-jd-2:/node
    environment:
      BESU_IDENTITY: "archivenode-jd-2"
    depends_on:
      - validator-bcb-1