data-path="/node/data"
genesis-file="/node/genesis.json"
logging="INFO"
host-allowlist=["*"]
rpc-http-enabled=true
rpc-http-port=8545
rpc-http-cors-origins=["*"]
nat-method="NONE"
p2p-port=30303
discovery-enabled=true